---
dependencies: []
galaxy_info:
  author: ShadowWalker
  company: ShadowWalker DevOps
  description: Common system configuration tasks
  galaxy_tags:
    - system
    - common
    - ubuntu
  license: MIT
  min_ansible_version: "2.12"
