---
dependencies: []
galaxy_info:
  author: Michael Buluma
  company: none
  description: Install vim on your system.
  galaxy_tags:
    - vim
    - server
    - sudo
    - system
  license: Apache-2.0
  min_ansible_version: '2.10'
  namespace: buluma
  platforms:
    - name: Fedora
      versions:
        - 33
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  role_name: vim
