---
- ansible.builtin.apt:
    name: openjdk-8-jdk
  name: Install Java 1.8
- ansible.builtin.group:
    name: tomcat
  name: Add group "tomcat"
- ansible.builtin.user:
    createhome: 'no'
    group: tomcat
    home: /usr/share/tomcat
    name: tomcat
  become: true
  become_method: sudo
  name: Add user "tomcat"
- ansible.builtin.file:
    group: tomcat
    owner: tomcat
    path: /usr/share/tomcat
    state: directory
  name: Create a tomcat directory
- ansible.builtin.get_url:
    dest: '{{ tomcat_download_location }}'
    url: '{{ tomcat_download_url }}'
  name: Download Tomcat
- ansible.builtin.unarchive:
    creates: /usr/share/tomcat/bin
    dest: /usr/share/tomcat
    extra_opts: --strip-components=1
    group: tomcat
    owner: tomcat
    remote_src: true
    src: '{{ tomcat_download_location }}'
  name: Extract tomcat archive
- ansible.builtin.template:
    dest: /etc/systemd/system/tomcat.service
    src: templates/tomcat.service.j2
  name: Copy tomcat service file
  when: ansible_service_mgr == "systems"
- ansible.builtin.service:
    daemon_reload: true
    enabled: true
    name: tomcat
    state: started
  name: Start and enable tomcat
  when: ansible_service_mgr == "systemd"
