---
- name: Install Java 1.8
  ansible.builtin.apt:
    name: openjdk-8-jdk
- name: Add group "tomcat"
  ansible.builtin.group:
    name: tomcat
- name: Add user "tomcat"
  ansible.builtin.user:
    createhome: "no"
    group: tomcat
    home: /usr/share/tomcat
    name: tomcat
  become: true
- name: Tomcat | Create a tomcat directory
  ansible.builtin.file:
    group: tomcat
    mode: '0755'
    owner: tomcat
    path: /usr/share/tomcat
    state: directory
- name: Tomcat | Download Tomcat
  ansible.builtin.get_url:
    dest: "{{ tomcat_download_location }}"
    mode: '0644'
    url: "{{ tomcat_download_url }}"
- name: Tomcat | Extract tomcat archive
  ansible.builtin.unarchive:
    creates: /usr/share/tomcat/bin
    dest: /usr/share/tomcat
    extra_opts: --strip-components=1
    group: tomcat
    mode: '0755'
    owner: tomcat
    remote_src: true
    src: "{{ tomcat_download_location }}"
- name: Tomcat | Copy tomcat service file
  ansible.builtin.template:
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
    src: templates/tomcat.service.j2
  when: ansible_facts['service_mgr'] == "systemd"
- name: Tomcat | Start and enable tomcat
  ansible.builtin.service:
    daemon_reload: true
    enabled: true
    name: tomcat
    state: started
  when: ansible_facts['service_mgr'] == "systemd"
