---
- name: Web | Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Web | Install PHP-FPM
  ansible.builtin.apt:
    name:
      - php
      - php-fpm
      - php-common
      - php-cli
      - php-curl
    state: present
- name: Web | Configure php.ini
  ansible.builtin.blockinfile:
    backup: true
    block: "date.time = Asia/Jakarta\ncgi-fix_pathinfo = 0\n"
    dest: /etc/php/{{ php_version }}/fpm/php.ini
  notify: restart php-fpm
