---
  - ansible.builtin.copy:
      backup: true
      dest: /etc/apt/
      src: sources.list
    name: Change repository Ubuntu 18.04Step 4 - Setup 'web' Roles
  - ansible.builtin.apt:
      update_cache: true
      upgrade: dist
    name: Update repository and Upgrade packages
  - community.general.timezone:
      name: Africa/Nairobi
    name: Set timezone to Africa/Nairobi
