---
- name: composer | Download composer
  ansible.builtin.get_url:
    dest: /tmp/installer
    mode: '0644'
    url: https://getcomposer.org/installer
- name: composer | Install composer
  ansible.builtin.shell: set -o pipefail && cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer.phar
    executable: /bin/bash
- name: composer | Rename composer.phar to composer
  ansible.builtin.command: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: composer | Make composer executable
  ansible.builtin.file:
    mode: '0755'
    path: /usr/local/bin/composer
    state: file
