---
- name: LeMP | Verify package manager on Fedora
  when: ansible_facts['distribution'] == "Fedora"
  block:
    - name: LeMP | Verify mutually exclusive parameters error
      ansible.builtin.dnf:
        name: at
        state: present
        use: yum
        use_backend: yum
      register: lemp_dnf_result
      ignore_errors: true
    - name: LeMP | Verify error message
      ansible.builtin.assert:
        that:
          - "'parameters are mutually exclusive' in lemp_dnf_result.msg"
          - not lemp_dnf_result is changed
    - name: LeMP | Verify package installation with use parameter
      ansible.builtin.dnf:
        name: at
        state: present
        use: dnf
      register: lemp_dnf_result
    - name: LeMP | Verify installation result
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
    - name: LeMP | Remove at package with use parameter
      ansible.builtin.dnf:
        name: at
        state: absent
        use: dnf
      register: lemp_dnf_result
    - name: LeMP | Verify package removal
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
    - name: LeMP | Verify package installation with use_backend parameter
      ansible.builtin.dnf:
        name: at
        state: present
        use_backend: dnf
      register: lemp_dnf_result
    - name: LeMP | Verify installation result with use_backend
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
    - name: LeMP | Remove at package with use_backend parameter
      ansible.builtin.dnf:
        name: at
        state: absent
        use_backend: dnf
      register: lemp_dnf_result
    - name: LeMP | Verify package removal with use_backend
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
    - name: LeMP | Verify package installation without parameters
      ansible.builtin.dnf:
        name: at
        state: present
      register: lemp_dnf_result
    - name: LeMP | Verify installation result without parameters
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
    - name: LeMP | Remove at package without parameters
      ansible.builtin.dnf:
        name: at
        state: absent
      register: lemp_dnf_result
    - name: LeMP | Verify package removal without parameters
      ansible.builtin.assert:
        that:
          - lemp_dnf_result is changed
- name: LeMP | Include PHP 5.6 tasks
  ansible.builtin.include_tasks: lemp-php56.yml
- name: LeMP | Include PHP 7.0 tasks
  ansible.builtin.include_tasks: lemp-php70.yml
- name: LeMP | Include Composer tasks
  ansible.builtin.include_tasks: composer.yml
- name: LeMP | Include Nginx tasks
  ansible.builtin.include_tasks: nginx.yml
- name: LeMP | Include Sendmail tasks
  ansible.builtin.include_tasks: sendmail.yml
- name: LeMP | Include Root Config tasks
  ansible.builtin.include_tasks: root-config.yml
- name: LeMP | Install all updates
  ansible.builtin.dnf:
    name: '*'
    state: present
