---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx16
    state: present
  notify:
    - restart nginx

- name: Make /var/lib/nginx/cache directory
  ansible.builtin.file:
    path: /var/lib/nginx/cache
    state: directory
    owner: nginx
    group: nginx
    mode: 700
  notify:
    - restart nginx

- name: Make /etc/nginx/ssl directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    owner: nginx
    group: nginx
    mode: 700
  notify:
    - restart nginx
