- ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  name: Install Sendmail
  with_items:
  - sendmail
  - sendmail-cf
  - make
  - mailx
- ansible.builtin.dnf:
    name: postfix
    state: absent
  name: Remove Postfix
- ansible.builtin.copy:
    dest: /etc/mail/aliases
    src: /etc/aliases
  name: Copy Sendmail config
- ansible.builtin.service:
    enabled: true
    name: sendmail
  name: Enable Sendmail service
