---
- name: Install Sendmail
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - sendmail
    - sendmail-cf
    - make
    - mailx
- name: Remove Postfix
  ansible.builtin.dnf:
    name: postfix
    state: absent
- name: Copy Sendmail config
  ansible.builtin.copy:
    dest: /etc/mail/aliases
    src: /etc/aliases
- name: Enable Sendmail service
  ansible.builtin.service:
    enabled: true
    name: sendmail
