---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: true
  tags:
    - install_packages
- name: Ensure .vim/{autoload,bundle} directory exists
  ansible.builtin.file:
    mode: "0750"
    path: "{{ item }}"
    recurse: false
    state: directory
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"
- name: Ensure Pathogen is in place
  ansible.builtin.get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim
- name: Deploy plugins
  ansible.builtin.git:
    clone: true
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    recursive: false
    repo: "{{ item.url }}"
    update: true
  loop: "{{ plugins }}"
- name: Ensure .vimrc config in place
  ansible.builtin.copy:
    backup: true
    dest: "{{ vimrc }}"
    mode: "0640"
    src: vimrc
