---
- name: Vim | Install required packages
  ansible.builtin.package:
    name: "{{ vim_install_packages }}"
    state: present
  become: true
  tags:
    - install_packages
- name: Vim | Ensure .vim/{autoload,bundle} directory exists
  ansible.builtin.file:
    mode: "0750"
    path: "{{ item }}"
    recurse: false
    state: directory
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"
- name: Vim | Ensure Pathogen is in place
  ansible.builtin.get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    mode: '0644'
    url: https://tpo.pe/pathogen.vim
- name: Vim | Deploy plugins
  ansible.builtin.git:
    clone: true
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    recursive: false
    repo: "{{ item.url }}"
    version: "{{ item.version }}"
  loop: "{{ vim_plugins }}"
- name: Vim | Ensure .vimrc config in place
  ansible.builtin.copy:
    backup: true
    dest: "{{ vim_vimrc }}"
    mode: "0640"
    src: vimrc
