---
dependencies: []
galaxy_info:
  author: ShadowWalker
  company: ShadowWalker DevOps
  description: Web server configuration
  galaxy_tags:
    - web
    - nginx
    - php
  license: MIT
  min_ansible_version: "2.12"
