---
name: CI
true:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  lemp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Test Site Build
      run: ansible-playbook -K lemp.yml -vvv
  site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Test Site Build
      run: ansible-playbook -K sites.yml -vvv
  tomcat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Test Tomcat
      run: ansible-playbook -K roles/tomcat.yml -vvv
  vim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Test Vim
      run: ansible-playbook -K roles/vim-config.yaml -vvv
