---
name: Workflow
true:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: todo
        name: TODO to Issue
        uses: buluma/todo-to-issue-action@v1.0.1
        with:
          PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
          USER_PROJECTS: buluma/Ansible/To do
